name: Test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: install dependencies
        run: uv sync --frozen
      - name: run tests
        run: uv run pytest -q
