name: Test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: use python 3.11 environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: rag
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e . --no-deps
      - name: run rag test
        working-directory: rag
        run: pytest tests/ -q
      - name: install agent package
        working-directory: agent
        run: pip install -e . pytest
      - name: run agent tests
        working-directory: agent
        run: pytest tests/ -q
